import type { Listing } from './types';
import { buildListResult, mockSuccess } from '@/lib/mocks/mock-helpers';

const ADVERTISERS = {
  a2: { id: 2, firstName: 'Ahmed', lastName: 'Hassan', email: 'ahmed@LVN.com', phone: '+201001234567' },
  a3: { id: 3, firstName: 'Sara',  lastName: 'Ali',    email: 'sara@LVN.com',  phone: '+201112345678' },
  a4: { id: 4, firstName: 'Omar',  lastName: 'Khaled', email: 'omar@LVN.com',  phone: '+201223456789' },
  a5: { id: 5, firstName: 'Nour',  lastName: 'Samir',  email: 'nour@LVN.com',  phone: '+201334567890' },
};

const mockListings: Listing[] = [
  {
    id: 1,
    advertiser_id: 2,
    title: 'Luxury Villa in Palm Hills',
    description: 'Stunning 4-bedroom villa with private garden and pool access. Premium finishing and modern design.',
    property_type: 'villa',
    property_status: 'ready',
    city: 'Giza',
    city_id: 1,
    area_id: 1,
    project_id: 1,
    price: 12500000,
    is_cash_only: false,
    down_payment_amount: 15,
    installment_years: 7,
    built_up_area: 450,
    land_area: 600,
    bedrooms: 4,
    bathrooms: 5,
    floor: null,
    view: 'garden',
    address: null,
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Ahmed Hassan',
    contact_phone: '+201001234567',
    contact_whatsapp: '+201001234567',
    finishing: 'ultra_lux',
    delivery_year: null,
    listing_status: 'approved',
    is_featured: true,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a2,
    Area: { id: 1, name: '6th of October', city: 'Giza' },
    Project: { id: 1, name: 'Palm Hills', developer: 'Palm Hills Developments', city: 'Giza' },
  },
  {
    id: 2,
    advertiser_id: 3,
    title: 'Modern Apartment in Madinaty',
    description: 'Spacious 3-bedroom apartment with open view. Fully finished with AC units installed.',
    property_type: 'apartment',
    property_status: 'ready',
    city: 'Cairo',
    city_id: 2,
    area_id: 2,
    project_id: 2,
    price: 3200000,
    is_cash_only: true,
    down_payment_amount: null,
    installment_years: null,
    built_up_area: 185,
    land_area: null,
    bedrooms: 3,
    bathrooms: 2,
    floor: '3',
    view: 'open',
    address: null,
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Sara Ali',
    contact_phone: '+201112345678',
    contact_whatsapp: '+201112345678',
    finishing: 'fully_finished',
    delivery_year: null,
    listing_status: 'approved',
    is_featured: true,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a3,
    Area: { id: 2, name: 'Madinaty', city: 'Cairo' },
    Project: { id: 2, name: 'Madinaty', developer: 'TMG', city: 'Cairo' },
  },
  {
    id: 3,
    advertiser_id: 4,
    title: 'Penthouse in Zayed',
    description: 'Exclusive penthouse with panoramic city views. Private roof terrace with jacuzzi.',
    property_type: 'duplex',
    property_status: 'ready',
    city: 'Giza',
    city_id: 1,
    area_id: 3,
    project_id: 3,
    price: 8500000,
    is_cash_only: false,
    down_payment_amount: 20,
    installment_years: 5,
    built_up_area: 320,
    land_area: null,
    bedrooms: 4,
    bathrooms: 4,
    floor: 'roof',
    view: 'city',
    address: null,
    finishing: 'super_lux',
    delivery_year: null,
    listing_status: 'approved',
    is_featured: false,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a4,
    Area: { id: 3, name: 'Sheikh Zayed', city: 'Giza' },
    Project: { id: 3, name: 'Zayed Heights', developer: 'Zayed Developments', city: 'Giza' },
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Ahmed Hassan',
    contact_phone: '+201001234567',
    contact_whatsapp: '+201001234567',
  },
  {
    id: 4,
    advertiser_id: 5,
    title: 'Studio in Downtown Cairo',
    description: 'Cozy studio apartment perfect for singles or young couples. Walking distance to metro.',
    property_type: 'studio',
    property_status: 'ready',
    city: 'Cairo',
    city_id: 3,
    area_id: 9,
    project_id: null,
    price: 950000,
    is_cash_only: true,
    down_payment_amount: null,
    installment_years: null,
    built_up_area: 55,
    land_area: null,
    bedrooms: 0,
    bathrooms: 1,
    floor: '5',
    view: null,
    address: null,
    finishing: 'fully_finished',
    delivery_year: null,
    listing_status: 'approved',
    is_featured: false,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a5,
    Area: { id: 9, name: 'Downtown', city: 'Cairo' },
    Project: null,
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Sara Ali',
    contact_phone: '+201112345678',
    contact_whatsapp: '+201112345678',
  },
  {
    id: 5,
    advertiser_id: 5,
    title: 'Townhouse in Mostakbal City',
    description: 'Modern townhouse in prime location. 0% down payment for limited time offer.',
    property_type: 'townhouse',
    property_status: 'offplan',
    city: 'Cairo',
    city_id: 1,
    area_id: 1,
    project_id: 5,
    price: 5800000,
    is_cash_only: false,
    down_payment_amount: 0,
    installment_years: 10,
    built_up_area: 220,
    land_area: 300,
    bedrooms: 3,
    bathrooms: 3,
    floor: null,
    view: 'garden',
    address: null,
    finishing: 'semi_finished',
    delivery_year: 2026,
    listing_status: 'approved',
    is_featured: true,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a5,
    Area: { id: 1, name: 'Mostakbal City', city: 'Cairo' },
    Project: { id: 5, name: 'Mostakbal', developer: 'Inertia', city: 'Cairo' },
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Sara Ali',
    contact_phone: '+201112345678',
    contact_whatsapp: '+201112345678',
  },
  {
    id: 6,
    advertiser_id: 5,
    title: 'Chalet in North Coast',
    description: 'Beachfront chalet with stunning sea views. Part of exclusive resort community.',
    property_type: 'chalet',
    property_status: 'offplan',
    city: 'North Coast',
    city_id: 2,
    area_id: 2,
    project_id: 6,
    price: 4200000,
    is_cash_only: false,
    down_payment_amount: 10,
    installment_years: 8,
    built_up_area: 120,
    land_area: null,
    bedrooms: 2,
    bathrooms: 2,
    floor: null,
    view: 'sea',
    address: null,
    finishing: 'fully_finished',
    delivery_year: 2025,
    listing_status: 'approved',
    is_featured: true,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a5,
    Area: { id: 2, name: 'Ras El Hekma', city: 'North Coast' },
    Project: { id: 6, name: 'Hacienda Bay', developer: 'Palm Hills', city: 'North Coast' },
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Sara Ali',
    contact_phone: '+201112345678',
    contact_whatsapp: '+201112345678',
  },
  {
    id: 7,
    advertiser_id: 5,
    title: 'Twin House in New Capital',
    description: 'Luxurious twin house in the heart of the New Administrative Capital. Smart home features included.',
    property_type: 'twin_house',
    property_status: 'offplan',
    city: 'New Capital',
    city_id: 4,
    area_id: 3,
    project_id: 7,
    price: 7200000,
    is_cash_only: false,
    down_payment_amount: 5,
    installment_years: 10,
    built_up_area: 280,
    land_area: 350,
    bedrooms: 4,
    bathrooms: 4,
    floor: null,
    view: null,
    address: null,
    finishing: 'core_shell',
    delivery_year: 2027,
    listing_status: 'approved',
    is_featured: false,
    admin_comment: null,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    created_at: '2025-12-26T20:52:16.380Z',
    updated_at: '2025-12-26T20:52:16.380Z',
    Advertiser: ADVERTISERS.a5,
    Area: { id: 3, name: 'R7', city: 'New Capital' },
    Project: { id: 7, name: 'Midtown Solo', developer: 'Better Home', city: 'New Capital' },
    video_url: 'https://example.com/video',
    tour_url: 'https://example.com/tour',
    contact_name: 'Sara Ali',
    contact_phone: '+201112345678',
    contact_whatsapp: '+201112345678',
  },
];

export const mockListingsList = buildListResult(mockListings, 1, 5);
export const mockListingItem = { success: true, data: mockListings[0] };
export const mockListingSuccess = mockSuccess('Listing updated');
export const mockUploadImages = {
  data: ['https://placehold.co/800x600/png', 'https://placehold.co/800x600/png'],
};
