import type { Listing } from './types';
import { buildListResult, mockSuccess } from '@/lib/mocks/mock-helpers';

const mockListings: Listing[] = [
  {
    id: 'listing-001',
    property_status: 'ready',
    property_type: 'apartment',
    city: 'Cairo',
    area: 'New Cairo',
    project_name: 'Midtown',
    title: '3-Bedroom Apartment in Midtown',
    description: 'Spacious apartment with modern finishing in the heart of New Cairo.',
    price: 4500000,
    built_up_area: 180,
    bedrooms: 3,
    bathrooms: 2,
    finishing: 'fully-finished',
    down_payment_percentage: 20,
    installment_years: 5,
    advertiser_id: 'adv-001',
    advertiser_name: 'Elite Properties',
    is_featured: true,
    listing_status: 'approved',
    images: [],
    approved_at: '2026-04-15T10:00:00Z',
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-04-15T10:00:00Z',
  },
  {
    id: 'listing-002',
    property_status: 'offplan',
    property_type: 'villa',
    city: 'Giza',
    area: '6th of October',
    project_name: 'Palm Hills',
    title: '4-Bedroom Villa in Palm Hills',
    description: 'Luxury villa with private garden in Palm Hills.',
    price: 12000000,
    built_up_area: 420,
    bedrooms: 4,
    bathrooms: 3,
    finishing: 'semi-finished',
    delivery_year: 2027,
    down_payment_percentage: 15,
    installment_years: 8,
    advertiser_id: 'adv-002',
    advertiser_name: 'Palm Hills Developments',
    is_featured: false,
    listing_status: 'pending',
    images: [],
    created_at: '2026-05-01T09:00:00Z',
  },
  {
    id: 'listing-003',
    property_status: 'ready',
    property_type: 'studio',
    city: 'Alexandria',
    area: 'Smouha',
    title: 'Studio in Smouha',
    price: 900000,
    built_up_area: 60,
    bedrooms: 0,
    bathrooms: 1,
    finishing: 'fully-finished',
    advertiser_id: 'adv-003',
    advertiser_name: 'Alex Realty',
    is_featured: false,
    listing_status: 'rejected',
    images: [],
    rejected_at: '2026-04-20T14:00:00Z',
    admin_comment: 'Incomplete documentation.',
    created_at: '2026-04-18T11:00:00Z',
    updated_at: '2026-04-20T14:00:00Z',
  },
];

export const mockListingsList = buildListResult(mockListings, 1, 20);
export const mockListingItem = { success: true, data: mockListings[0] };
export const mockListingSuccess = mockSuccess('Listing updated');
export const mockUploadImages = {
  data: ['https://placehold.co/800x600/png', 'https://placehold.co/800x600/png'],
};
