import type { Application, ApplicationDetail } from '@/lib/eyoot-types';
import { buildPaginatedResult, mockSuccess } from '@/lib/mocks/mock-helpers';

const baseApplications: Application[] = [
  {
    id: 101,
    studentId: 12,
    studentName: 'Sara Mahmoud',
    studentEmail: 'sara.mahmoud@example.com',
    studentUsername: 'sara_m',
    companyId: 3,
    companyName: 'Orbit Labs',
    companyLogo: '',
    positionId: 14,
    positionTitle: 'Frontend Intern',
    status: 'interview',
    ibmProofStatus: 'approved',
    interviewStatus: 'scheduled',
    volunteeringStatus: 'pending',
    certificateStatus: 'not-ready',
    capacityWarning: false,
    appliedAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-08T12:30:00Z',
    notes: 'Strong portfolio and solid communication skills.',
  },
  {
    id: 102,
    studentId: 18,
    studentName: 'Omar Ali',
    studentEmail: 'omar.ali@example.com',
    studentUsername: 'omar_ali',
    companyId: 7,
    companyName: 'Nimbus Tech',
    companyLogo: '',
    positionId: 22,
    positionTitle: 'Data Intern',
    status: 'ibm-course-required',
    ibmProofStatus: 'pending',
    interviewStatus: 'pending',
    volunteeringStatus: 'not-required',
    certificateStatus: 'not-ready',
    capacityWarning: true,
    appliedAt: '2026-04-26T08:15:00Z',
    updatedAt: '2026-05-06T09:10:00Z',
  },
  {
    id: 103,
    studentId: 25,
    studentName: 'Mona Saad',
    studentEmail: 'mona.saad@example.com',
    studentUsername: 'mona_saad',
    companyId: 9,
    companyName: 'Atlas Growth',
    companyLogo: '',
    positionId: 31,
    positionTitle: 'Marketing Intern',
    status: 'approved',
    ibmProofStatus: 'approved',
    interviewStatus: 'completed',
    volunteeringStatus: 'completed',
    certificateStatus: 'uploaded',
    capacityWarning: false,
    appliedAt: '2026-04-12T13:05:00Z',
    updatedAt: '2026-05-02T16:45:00Z',
  },
];

export const mockApplicationsList = buildPaginatedResult(baseApplications, 1, 20);

export const mockApplicationDetail: ApplicationDetail = {
  ...baseApplications[0],
  ibmProof: {
    id: 201,
    studentId: 12,
    studentName: 'Sara Mahmoud',
    studentEmail: 'sara.mahmoud@example.com',
    applicationId: 101,
    companyName: 'Orbit Labs',
    positionTitle: 'Frontend Intern',
    courseTitle: 'IBM Frontend Foundations',
    courseUrl: 'https://example.com/ibm-frontend',
    proofUrl: 'https://example.com/proof-frontend.png',
    proofType: 'image',
    status: 'approved',
    uploadedAt: '2026-04-20T09:10:00Z',
  },
  interviewSlot: {
    id: 301,
    date: '2026-05-20',
    time: '14:00',
    location: 'Zoom',
    link: 'https://zoom.us/j/123456789',
    deadline: '2026-05-18',
    allowRescheduling: true,
    status: 'scheduled',
  },
  certificate: {
    id: 401,
    studentId: 12,
    studentName: 'Sara Mahmoud',
    studentEmail: 'sara.mahmoud@example.com',
    applicationId: 101,
    companyName: 'Orbit Labs',
    positionTitle: 'Frontend Intern',
    title: 'Internship Completion Certificate',
    fileUrl: 'https://example.com/certificates/101.pdf',
    completionDate: '2026-07-15',
    uploadedAt: '2026-07-16T10:00:00Z',
    isNotified: true,
  },
  internalNotes: ['Follow up on interview schedule'],
  statusHistory: [
    { status: 'applied', date: '2026-05-01', adminName: 'Admin A' },
    { status: 'ibm-course-required', date: '2026-05-03', adminName: 'Admin B' },
    { status: 'interview', date: '2026-05-08', adminName: 'Admin B' },
  ],
};

export const mockApplicationSuccess = mockSuccess('Application updated');
